### ISSUE TITLE
[Parent Issue] Configure the repository to our requirements

### ISSUE THREAD

**Issue by jaylenw** [CityOfLosAngeles/fetch-latest-github-release#1]
### Problem

We have created this repository from a fork and plan on using this repository for our projects. Therefore the following will need to be done before we begin with development and publishing a release.

### Solution

Carryout the following:

- [x] Enable Private Vulnerability reporting
- [x] Enable Dependabot alerts
- [x] Enable Dependabot security updates
- [x] Enable Dependabot version updates #18 
- [x] Enable Secret Scanning
- [x] Enable Code Scanning
- [x] Configure ITA's Release Manager
- [x] Enable Secret Scanning
- [x] Enable Branch Protections
- [x] Configure CODEOWNERS #3 
- [x] Modify LICENSE.md #3 
- [x] Setup Security Policy / ADD SECURITY.md #5 
- [x] Add Unit Tests #7 
- [x] Add GitHub Issue & PR template #3 
- [ ] Add CONTRIBUTOR.md
- [ ] Add Code of Conduct Doc
- [ ] Enable Reporting of Content
